### ISSUE TITLE
Erro, o elemento `/html/body/div[2]/div[4]/div/div[1]/div[4]/div[2]/div` nao existe

### ISSUE THREAD

**Issue by matheustavaresdev** [DanielHe4rt/bbbot#15]
```
node:6559) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "/html/body/div[2]/div[4]/div/div[1]/div[4]/div[2]/div" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/matheustavares/TavAppsDev/bbbot/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/matheustavares/TavAppsDev/bbbot/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (/Users/matheustavares/TavAppsDev/bbbot/node_modules/puppeteer/lib/DOMWorld.js:441:17)
    at Frame.waitForXPath (/Users/matheustavares/TavAppsDev/bbbot/node_modules/puppeteer/lib/FrameManager.js:642:47)
    at Frame.<anonymous> (/Users/matheustavares/TavAppsDev/bbbot/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForXPath (/Users/matheustavares/TavAppsDev/bbbot/node_modules/puppeteer/lib/Page.js:1131:29)
    at /Users/matheustavares/TavAppsDev/bbbot/index.js:47:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6559) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6559) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by matheustavaresdev** [comment]
Depois de abrir o script, ele ira fazer login, entao clique no site pra votacao da manu e ele funciona!

**Comment by matheustavaresdev** [comment]
+
